import type { FaqPiece } from "../types";

export const faqPieces: FaqPiece[] = [
  {
    name: "Sukuna",
    role: "king",
    summary: "Центр всей партии. Давит ближней угрозой и раскрывает РТ через захват зоны.",
    techniqueKeys: ["sukuna"],
    domainName: "Sukuna",
  },
  {
    name: "Gojo",
    role: "queen",
    summary: "Главный дальний контролёр. Синий, Красный и Фиолетовый идут по циклу и меняют темп поля.",
    techniqueKeys: ["gojo_blue", "gojo_red", "gojo_purple"],
    domainName: "Gojo",
  },
  {
    name: "Yuta",
    role: "rook",
    summary: "Сильнее всего раскрывается через копирование чужих техник. Его сила зависит от окружения.",
    techniqueKeys: [],
    domainName: "Yuta",
  },
  {
    name: "Jogo",
    role: "rook",
    summary: "Контроль прямых линий и огненное давление через лаву.",
    techniqueKeys: ["jogo"],
    domainName: "Jogo",
  },
  {
    name: "Kenjaku",
    role: "bishop",
    summary: "Ломает построения пешек, двигает чужой фронт и вскрывает линии.",
    techniqueKeys: ["kenjaku"],
    domainName: "Kenjaku",
  },
  {
    name: "Mahito",
    role: "bishop",
    summary: "Играет от искажения и вынуждает соперника тратить ходы на спасение фигур.",
    techniqueKeys: ["mahito"],
    domainName: "Mahito",
  },
  {
    name: "Yuki",
    role: "knight",
    summary: "Резкие позиционные врывы, притяжение целей и давление массы вблизи.",
    techniqueKeys: ["yuki"],
    domainName: "Yuki",
  },
  {
    name: "Dagon",
    role: "knight",
    summary: "Локальный контроль зоны. Выталкивает цели и режет чужие техники в ближнем радиусе.",
    techniqueKeys: ["dagon"],
    domainName: "Dagon",
  },
  {
    name: "Yuji",
    role: "pawn",
    summary: "Лобовая пешка с прямым пробоем вперёд.",
    techniqueKeys: ["yuji"],
  },
  {
    name: "Megumi",
    role: "pawn",
    summary: "Жертвенная пешка. Может уничтожить себя и на последних рядах врага призвать Махорагу.",
    techniqueKeys: ["megumi"],
  },
  {
    name: "Mahoraga",
    role: "pawn",
    summary: "Призванная фигура Мэгуми. Сначала ходит как пешка, затем через прокрут колеса расширяет набор движений.",
    techniqueKeys: ["mahoraga"],
  },
  {
    name: "Nobara",
    role: "pawn",
    summary: "Пометка цели и запрет на технику. Хороша для подготовки размена.",
    techniqueKeys: ["nobara"],
  },
  {
    name: "Nanami",
    role: "pawn",
    summary: "Дальняя диагональная казнь через 7:3.",
    techniqueKeys: ["nanami"],
  },
  {
    name: "Choso",
    role: "pawn",
    summary: "Линейный прокол на 1–2 клетки по чистой линии.",
    techniqueKeys: ["choso"],
  },
  {
    name: "Todo",
    role: "pawn",
    summary: "Меняет позиции союзных пешек и ломает построение фронта.",
    techniqueKeys: ["todo"],
  },
  {
    name: "Maki",
    role: "pawn",
    summary: "Простая и жёсткая пешка с бесплатным фронтальным добиванием.",
    techniqueKeys: ["maki"],
  },
  {
    name: "Inumaki",
    role: "pawn",
    summary: "Контроль соседней клетки через Проклятую Речь.",
    techniqueKeys: ["inumaki"],
  },
];
